### ISSUE TITLE
Audio download is broken

### ISSUE THREAD

**Issue by Flameborn** [IljaN/narr#4] opened 2024-06-02 22:57 UTC
Hello,

In case this software is still being updated, it looks like audio downloads are currently broken.

From what I can see, navigate events do not always fire, and the initial navigation to an episode/movie does not start the download.

The media URL format is still the same.

Tried via MacOS Brave 1.61 and 1.66.

**Comment by IljaN** [comment] 2024-06-05 16:12
Thanks for reporting. Are you seeing any errors in the CLI output?

**Comment by Flameborn** [comment] 2024-06-05 22:22
None unfortunately. For the initial URL, not even downloads starting, navigatedTo messages, etc. The last message printed is about the successful connection to the remote debugger.

If I navigate to e.g. the homepage, and if the navigate event is logged, which rarely happens, I get:

```
ERROR: 2024/06/03 00:39:28 logger.go:39: runtime error: error probing file format: error reading header: EOF
```

**Comment by IljaN** [comment] 2024-07-01 11:43
I could reproduce the issue. On Mac Netflix seems to send a different mpeg4 container format than on Linux. (mp42 vs iso6). 

> ERROR: 2024/06/03 00:39:28 logger.go:39: runtime error: error probing file format: error reading header: EOF

This happens as sometimes netflix sends 403 (Fobidden) instead of the audio file. Maybe because the authentication token expires and needs a refresh.

I am working on a fix.

**Comment by Flameborn** [comment] 2024-07-03 09:18
That is a very interesting find, perhaps they do this on Linux for compatibility reasons.

AT any rate, thank you so much for the update and for the fix in advance.

**Comment by jiayugz** [comment] 2024-07-26 20:13
I ran into similar problems today.
the error message is :  wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by Hygros** [comment] 2024-07-31 15:19
Hi, I have the same error. Everything worked fine until yesterday. I run Windows Version 10.0.19045 Build 19045
Now I get this:
ERROR: 2024/07/31 17:15:47 logger.go:39: runtime error: error probing file format: error reading header: EOF
Any ideas? Thanks

**Comment by IljaN** [comment] 2024-09-29 01:14
@Flameborn @Hygros  Sorry for the delay, please try the [latest release](https://github.com/IljaN/narr/releases/tag/0.2.0). Downloads on macOS should work now. Probing also got more stable, but might require some retry logic in case the token expires.

Please let me know. Thank you very much, and thanks again for your patience.

**Comment by IljaN** [comment] 2024-09-29 01:16
@jiayugz Opened a separate issue here #7

**Comment by Flameborn** [comment] 2024-09-29 11:58
Huge thanks @IljaN, it works beautifully here (Intel MacOS 12.7.6).

I have not experienced the mentioned issues so far.

**Closed** 2024-09-30 06:07 UTC
